<!-- <!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<link rel="stylesheet" href="css/estilos.css">
	<link rel="stylesheet" href="<?= URL ?>css/test/estilos.css">
	<title>home</title>

</head>

<body>
-->
	<br>
	<div class="container">
		<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
			<ol class="carousel-indicators">
				<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
				<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
				<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
			</ol>
			<div class="carousel-inner">
				<div class="carousel-item active">
					<img src="img/desarrollo.jpg" class="d-block w-100" width="1200" height="600" alt="...">
				</div>
				<div class="carousel-item">
					<img src="img/deportivo.jpg" class="d-block w-100" width="1000" height="600" alt="...">
				</div>
				<div class="carousel-item">
					<img src="img/caballo.jpg" class="d-block w-100" width="900" height="600" alt="...">
				</div>
			</div>
			<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
				<span class="carousel-control-prev-icon" aria-hidden="true"></span>
				<span class="sr-only">Previous</span>
			</a>
			<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
				<span class="carousel-control-next-icon" aria-hidden="true"></span>
				<span class="sr-only">Next</span>
			</a>
		</div>
	</div>
	<br>
	<h1 style="text-align: center;">BIENVENIDOS</h1>
	<br>
	<div class="container">
		<div class="row row-cols-1 row-cols-md-2">
			<div class="col mb-4">
				<div class="card">
					<img src="img/mat.png" class="card-img-top" alt="...">
					<div class="card-body">
						<h5 class="card-title">Esperanza Matemática</h5>
					</div>
				</div>
			</div>
			<div class="col mb-4">
				<div class="card">
					<img src="img/pro.png" class="card-img-top" alt="...">
					<div class="card-body">
						<h5 class="card-title">Probavilidad de Casa de Apuesta</h5>
					</div>
				</div>
			</div>
			<div class="col mb-4">
				<div class="card">
					<img src="img/gan.png" class="card-img-top" alt="...">
					<div class="card-body">
						<h5 class="card-title">Ganancia Neta</h5>
					</div>
				</div>
			</div>
			<div class="col mb-4">
				<div class="card">
					<img src="img/roi.png" class="card-img-top" alt="...">
					<div class="card-body">
						<h5 class="card-title">Retorno de Inverción</h5>
					</div>
				</div>
			</div>
		</div>
	</div>
<!-- 
	<footer>
		<p>
			55
		</p>
	</footer>
</body>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</html> -->