<div class="row">
  <div class="col-sm-5">
    <h1>Esperanza Matemática</h1>

    <form action="<?= URL ?>apuestas/esperanza" method="POST">
      <div class="form-group">
        <label for="exampleInputEmail1">Cuota</label>
        <input type="number" name="cuota" class="form-control" value="<?= $params['cuota'] ?>" step="any">
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">Probabilidad(%)</label>
        <input type="number" name="prob" class="form-control" value="<?= $params['probabilidad'] ?>" step="1">
      </div>
      <button type="submit" class="btn btn-primary">Calcular</button>
      <p>La esperanza Matemática es : <?= $params['res'] == 0 ? "" : $params['res']  ?></p>
      <p><?= $params['esperanza'] != '' ? "La apuesta es: " . $params['esperanza'] : ''   ?></p>
    </form>
  </div>
</div>