
<div class="row">
  <div class="col-sm-5">
    <h1>Ganancia Neta</h1>

    <form action="<?= URL ?>apuestas/ganancianeta" method="POST">
      <div class="form-group">
        <label for="exampleInputEmail1">Apuesta(S/)</label>
        <input type="number" name="apuesta" class="form-control" value="<?= $params['apuesta'] ?>" step="1">
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">Cuota</label>
        <input type="number" name="cuota" class="form-control" value="<?= $params['cuota'] ?>" step="0.01">
      </div>
      <button type="submit" class="btn btn-primary">Calcular</button>
      <p>La ganancia Neta es : <?= $params['ganancia'] == 0 ? "" : $params['ganancia'] ?></p>
    </form>
  </div>
</div>