
<div class="row">
  <div class="col-sm-5">
    <h1>Probabilidad de casa de apuesta(PCA)</h1>
    <form action="<?= URL ?>apuestas/pca" method="POST">
      <div class="form-group">
        <label for="exampleInputEmail1">Cuota</label>
        <input type="number" name="cuota" class="form-control" value="<?= $params['cuota'] ?>" step="any">
      </div>
      <button type="submit" class="btn btn-primary">Calcular</button>
      <p><?= $params['res'] == 0 ? "" :"PCA: " . $params['res'] . "%"  ?></p>
    </form>
  </div>
</div>
